### ISSUE TITLE
Place_autocomplete SF3

### ISSUE THREAD

**Issue by juliensantos87** [fungio/FungioGoogleMapBundle#3]
Hi,

I'm trying to implemente the `place_autocomplete` form but it seem to be not working for SF3.
I get `Could not load type "places_autocomplete"`.

Do you plan to fix it?

Btw thanks for your fork

**Comment by fungio** [comment]
Hi
I'll have a look
Keep in touch

**Comment by fungio** [comment]
It's corrected. Juste get this bundle and https://github.com/fungio/fungio-google-map up to date
