### ISSUE TITLE
Google Maps API warning: SensorNotRequired

### ISSUE THREAD

**Issue by juliensantos87** [fungio/FungioGoogleMapBundle#4]
Hey

I have a google Maps warning on my front
`Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required`

https://developers.google.com/maps/documentation/javascript/error-messages?hl=fr
SensorNotRequired =>I think it's can be remove ?

Thank's

**Comment by fungio** [comment]
I've corrected this warning just a minute ago.

**Comment by juliensantos87** [comment]
👍 🎉
