### ISSUE TITLE
SF5 compatibility

### ISSUE THREAD

**Issue by gaelb80** [fungio/FungioGoogleMapBundle#9]
Hi, we could not actually install your fork in sf 5.2 due to a composer requirement unsatisfiable in json-builder

"symfony/property-access": "^2.7|^3.0|~4.0"

Can you fix the composer requirements in this file ?

thks !

**Comment by fungio** [comment]
Feel free to do a PR

**Comment by gaelb80** [comment]
That's done !

**Comment by fungio** [comment]
There is no open PR. Are you sure you made one ?

**Comment by gaelb80** [comment]
> There is no open PR. Are you sure you made one ?

https://github.com/fungio/ivory-json-builder/pull/1

**Comment by fungio** [comment]
Ok done.

**Comment by gaelb80** [comment]
ok thanks but not fully compatible with sf5 and new twig branch and namespace.
